<a href="https://colab.research.google.com/github/nikhilrssahu1/ML/blob/TCS/TCS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# 1. Install PySpark
!pip install pyspark

# 2. Start a Spark Session (Simulates the EMR Cluster)
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("AirbnbChallenge").getOrCreate()

# 3. Create the dummy CSV file
data = """id,NAME,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,Construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365
1001,Clean & quiet apt home by the park,8001,verified,Michael,Brooklyn,Kensington,40.64749,-73.97237,United States,US,FALSE,strict,Private room,2020,1000,150,10,9,10/19/2021,0.21,4,6,286
1001,Clean & quiet apt home by the park,8001,verified,Michael,Brooklyn,Kensington,40.64749,-73.97237,United States,US,FALSE,strict,Private room,2020,1000,150,10,9,10/19/2021,0.21,4,6,286
1002,Skylit Midtown Castle,8002,verified,Charlotte,Manhattan,Midtown,40.75362,-73.98377,United States,US,FALSE,moderate,Entire home/apt,2003,2000,200,30,45,5/21/2022,0.38,5,2,228
1003,THE VILLAGE OF HARLEM,8003,unconfirmed,Elise,Manhattan,Harlem,40.80902,-73.9419,United States,US,TRUE,flexible,Private room,2003,600,80,3,0,,,5,1,352
1004,Cozy Entire Floor of Brownstone,8004,verified,Michael,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,FALSE,moderate,Entire home/apt,2020,500,50,1,270,7/5/2019,4.64,3,1,322
1005,Entire Apt: Spacious Studio/Loft,8005,verified,Mike,Manhattan,East Harlem,40.79851,-73.94399,United States,US,FALSE,moderate,Entire home/apt,2009,800,,10,9,11/19/2018,0.1,5,1,289
1006,Large Furnished Room Near B'way,8006,verified,Matthew,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,US,TRUE,strict,Private room,2009,1200,240,2,430,6/24/2019,3.47,4,1,220
1007,Beautiful 1 Bedroom in Queens,8007,verified,Charlotte,Queens,Astoria,40.76489,-73.98493,United States,US,TRUE,strict,Private room,2015,1200,120,2,430,6/24/2019,3.47,5,1,220
1008,Staten Island Getaway,8008,verified,Mike,Staten Island,St. George,40.64749,-73.97237,United States,US,FALSE,strict,Entire home/apt,2020,900,180,10,9,10/19/2021,0.21,4,6,286
1009,Brooklyn Luxury,8009,verified,Michael,Brooklyn,Williamsburg,40.64749,-73.97237,United States,US,FALSE,strict,Private room,2020,1500,150,10,9,10/19/2021,0.21,5,6,286
"""

with open("analytics_airbnb_data.csv", "w") as f:
    f.write(data)

# 4. Read the data (Task 1 Simulation)
# Note: In the exam, you use 's3://...', here we use the local path
df = spark.read.option("header", "true").csv("analytics_airbnb_data.csv")

# Show the raw data
df.show()

Requirement already satisfied: pyspark in /usr/local/lib/python3.12/dist-packages (3.5.1)
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.12/dist-packages (from pyspark) (0.10.9.7)
+----+--------------------+-------+----------------------+---------+-------------------+--------------+--------+---------+-------------+------------+----------------+-------------------+---------------+-----------------+-----+-----------+--------------+-----------------+-----------+-----------------+------------------+------------------------------+----------------+
|  id|                NAME|host_id|host_identity_verified|host_name|neighbourhood_group| neighbourhood|     lat|     long|      country|country_code|instant_bookable|cancellation_policy|      room_type|Construction_year|price|service_fee|minimum_nights|number_of_reviews|last_review|reviews_per_month|review_rate_number|calculated_host_listings_count|availability_365|
+----+--------------------+-------+----------------------+---------+-------------------+--------------+--------+---------+-------------+------------+----------------+-------------------+---------------+-----------------+-----+-----------+--------------+-----------------+-----------+-----------------+------------------+------------------------------+----------------+
|1001|Clean & quiet apt...|   8001|              verified|  Michael|           Brooklyn|    Kensington|40.64749|-73.97237|United States|          US|           FALSE|             strict|   Private room|             2020| 1000|        150|            10|                9| 10/19/2021|             0.21|                 4|                             6|             286|
|1001|Clean & quiet apt...|   8001|              verified|  Michael|           Brooklyn|    Kensington|40.64749|-73.97237|United States|          US|           FALSE|             strict|   Private room|             2020| 1000|        150|            10|                9| 10/19/2021|             0.21|                 4|                             6|             286|
|1002|Skylit Midtown Ca...|   8002|              verified|Charlotte|          Manhattan|       Midtown|40.75362|-73.98377|United States|          US|           FALSE|           moderate|Entire home/apt|             2003| 2000|        200|            30|               45|  5/21/2022|             0.38|                 5|                             2|             228|
|1003|THE VILLAGE OF HA...|   8003|           unconfirmed|    Elise|          Manhattan|        Harlem|40.80902| -73.9419|United States|          US|            TRUE|           flexible|   Private room|             2003|  600|         80|             3|                0|       NULL|             NULL|                 5|                             1|             352|
|1004|Cozy Entire Floor...|   8004|              verified|  Michael|           Brooklyn|  Clinton Hill|40.68514|-73.95976|United States|          US|           FALSE|           moderate|Entire home/apt|             2020|  500|         50|             1|              270|   7/5/2019|             4.64|                 3|                             1|             322|
|1005|Entire Apt: Spaci...|   8005|              verified|     Mike|          Manhattan|   East Harlem|40.79851|-73.94399|United States|          US|           FALSE|           moderate|Entire home/apt|             2009|  800|       NULL|            10|                9| 11/19/2018|              0.1|                 5|                             1|             289|
|1006|Large Furnished R...|   8006|              verified|  Matthew|          Manhattan|Hell's Kitchen|40.76489|-73.98493|United States|          US|            TRUE|             strict|   Private room|             2009| 1200|        240|             2|              430|  6/24/2019|             3.47|                 4|                             1|             220|
|1007|Beautiful 1 Bedro...|   8007|              verified|Charlotte|             Queens|       Astoria|40.76489|-73.98493|United States|          US|            TRUE|             strict|   Private room|             2015| 1200|        120|             2|              430|  6/24/2019|             3.47|                 5|                             1|             220|
|1008|Staten Island Get...|   8008|              verified|     Mike|      Staten Island|    St. George|40.64749|-73.97237|United States|          US|           FALSE|             strict|Entire home/apt|             2020|  900|        180|            10|                9| 10/19/2021|             0.21|                 4|                             6|             286|
|1009|     Brooklyn Luxury|   8009|              verified|  Michael|           Brooklyn|  Williamsburg|40.64749|-73.97237|United States|          US|           FALSE|             strict|   Private room|             2020| 1500|        150|            10|                9| 10/19/2021|             0.21|                 5|                             6|             286|
+----+--------------------+-------+----------------------+---------+-------------------+--------------+--------+---------+-------------+------------+----------------+-------------------+---------------+-----------------+-----+-----------+--------------+-----------------+-----------+-----------------+------------------+------------------------------+----------------+

In [13]:
# Env

#def read_data(spark):
    # 1. Mention the bucket name
    # IMPORTANT: Replace 'airbnb-dataXXXXXX' with the ACTUAL bucket name from your Lab console
   # bucket_name = "airbnb-data123456789"

    # 2. Define the file path
    # The instructions say the data is inside the 'inputfile' folder
  # file_path = "s3://" + bucket_name + "/inputfile/analytics_airbnb_data.csv"

    # 3. Read the CSV file into a dataframe with header=True
   # df = spark.read.option("header", "true").csv(file_path)
   # df= spark.read.csv("s3_input_path,header=true")

    #df= spark.read

    # 4. Return the dataframe
  #  return df

In [14]:
#local
def read_data(spark):
    # In Colab, we just read the local file we created
    file_path = "analytics_airbnb_data.csv"

    df = spark.read.option("header", "true").csv(file_path)
    return df

# Run the function to verify it works
df = read_data(spark)
df.show(5)

+----+--------------------+-------+----------------------+---------+-------------------+-------------+--------+---------+-------------+------------+----------------+-------------------+---------------+-----------------+-----+-----------+--------------+-----------------+-----------+-----------------+------------------+------------------------------+----------------+
|  id|                NAME|host_id|host_identity_verified|host_name|neighbourhood_group|neighbourhood|     lat|     long|      country|country_code|instant_bookable|cancellation_policy|      room_type|Construction_year|price|service_fee|minimum_nights|number_of_reviews|last_review|reviews_per_month|review_rate_number|calculated_host_listings_count|availability_365|
+----+--------------------+-------+----------------------+---------+-------------------+-------------+--------+---------+-------------+------------+----------------+-------------------+---------------+-----------------+-----+-----------+--------------+-----------------+-----------+-----------------+------------------+------------------------------+----------------+
|1001|Clean & quiet apt...|   8001|              verified|  Michael|           Brooklyn|   Kensington|40.64749|-73.97237|United States|          US|           FALSE|             strict|   Private room|             2020| 1000|        150|            10|                9| 10/19/2021|             0.21|                 4|                             6|             286|
|1001|Clean & quiet apt...|   8001|              verified|  Michael|           Brooklyn|   Kensington|40.64749|-73.97237|United States|          US|           FALSE|             strict|   Private room|             2020| 1000|        150|            10|                9| 10/19/2021|             0.21|                 4|                             6|             286|
|1002|Skylit Midtown Ca...|   8002|              verified|Charlotte|          Manhattan|      Midtown|40.75362|-73.98377|United States|          US|           FALSE|           moderate|Entire home/apt|             2003| 2000|        200|            30|               45|  5/21/2022|             0.38|                 5|                             2|             228|
|1003|THE VILLAGE OF HA...|   8003|           unconfirmed|    Elise|          Manhattan|       Harlem|40.80902| -73.9419|United States|          US|            TRUE|           flexible|   Private room|             2003|  600|         80|             3|                0|       NULL|             NULL|                 5|                             1|             352|
|1004|Cozy Entire Floor...|   8004|              verified|  Michael|           Brooklyn| Clinton Hill|40.68514|-73.95976|United States|          US|           FALSE|           moderate|Entire home/apt|             2020|  500|         50|             1|              270|   7/5/2019|             4.64|                 3|                             1|             322|
+----+--------------------+-------+----------------------+---------+-------------------+-------------+--------+---------+-------------+------------+----------------+-------------------+---------------+-----------------+-----+-----------+--------------+-----------------+-----------+-----------------+------------------+------------------------------+----------------+
only showing top 5 rows

In [15]:
#Env
#def clean_data(input_df):
    # # 1. Drop the rows which contain null values
    # # "any" means if even one column is null, drop the row
    # df_no_nulls = input_df.na.drop()

    # # 2. Remove the duplicate rows
    # cleaned_df = df_no_nulls.dropDuplicates()

    # # 3. Return the final dataframe
    # return cleaned_df

In [16]:
def clean_data(input_df):
    # Drop rows with null values
    df_no_nulls = input_df.na.drop()

    # Remove duplicates
    cleaned_df = df_no_nulls.dropDuplicates()

    return cleaned_df

# Run the function
cleaned_df = clean_data(df)

# Show results to verify
print(f"Original Count: {df.count()}")
print(f"Cleaned Count: {cleaned_df.count()}")
cleaned_df.show()

Original Count: 10
Cleaned Count: 7
+----+--------------------+-------+----------------------+---------+-------------------+--------------+--------+---------+-------------+------------+----------------+-------------------+---------------+-----------------+-----+-----------+--------------+-----------------+-----------+-----------------+------------------+------------------------------+----------------+
|  id|                NAME|host_id|host_identity_verified|host_name|neighbourhood_group| neighbourhood|     lat|     long|      country|country_code|instant_bookable|cancellation_policy|      room_type|Construction_year|price|service_fee|minimum_nights|number_of_reviews|last_review|reviews_per_month|review_rate_number|calculated_host_listings_count|availability_365|
+----+--------------------+-------+----------------------+---------+-------------------+--------------+--------+---------+-------------+------------+----------------+-------------------+---------------+-----------------+-----+-----------+--------------+-----------------+-----------+-----------------+------------------+------------------------------+----------------+
|1002|Skylit Midtown Ca...|   8002|              verified|Charlotte|          Manhattan|       Midtown|40.75362|-73.98377|United States|          US|           FALSE|           moderate|Entire home/apt|             2003| 2000|        200|            30|               45|  5/21/2022|             0.38|                 5|                             2|             228|
|1006|Large Furnished R...|   8006|              verified|  Matthew|          Manhattan|Hell's Kitchen|40.76489|-73.98493|United States|          US|            TRUE|             strict|   Private room|             2009| 1200|        240|             2|              430|  6/24/2019|             3.47|                 4|                             1|             220|
|1007|Beautiful 1 Bedro...|   8007|              verified|Charlotte|             Queens|       Astoria|40.76489|-73.98493|United States|          US|            TRUE|             strict|   Private room|             2015| 1200|        120|             2|              430|  6/24/2019|             3.47|                 5|                             1|             220|
|1008|Staten Island Get...|   8008|              verified|     Mike|      Staten Island|    St. George|40.64749|-73.97237|United States|          US|           FALSE|             strict|Entire home/apt|             2020|  900|        180|            10|                9| 10/19/2021|             0.21|                 4|                             6|             286|
|1009|     Brooklyn Luxury|   8009|              verified|  Michael|           Brooklyn|  Williamsburg|40.64749|-73.97237|United States|          US|           FALSE|             strict|   Private room|             2020| 1500|        150|            10|                9| 10/19/2021|             0.21|                 5|                             6|             286|
|1001|Clean & quiet apt...|   8001|              verified|  Michael|           Brooklyn|    Kensington|40.64749|-73.97237|United States|          US|           FALSE|             strict|   Private room|             2020| 1000|        150|            10|                9| 10/19/2021|             0.21|                 4|                             6|             286|
|1004|Cozy Entire Floor...|   8004|              verified|  Michael|           Brooklyn|  Clinton Hill|40.68514|-73.95976|United States|          US|           FALSE|           moderate|Entire home/apt|             2020|  500|         50|             1|              270|   7/5/2019|             4.64|                 3|                             1|             322|
+----+--------------------+-------+----------------------+---------+-------------------+--------------+--------+---------+-------------+------------+----------------+-------------------+---------------+-----------------+-----+-----------+--------------+-----------------+-----------+-----------------+------------------+------------------------------+----------------+

In [17]:
#ENV
# def S3_load_data(data, file_name, output_path):
#     # 1. Mention the bucket name inside the variable
#     # REPLACE THIS with your actual bucket name
#     bucket_name = "airbnb-data123456789"

#     # 2. Construct the full S3 path
#     # Format: s3://{bucket_name}/{output_path}/{file_name}
#     full_path = "s3://{}/{}/{}".format(bucket_name, output_path, file_name)

#     # 3. Write the code to store the output
#     # - coalesce(1): Ensures it saves as a SINGLE file (Single Partition)
#     # - mode("overwrite"): Overwrites if file exists (good for testing)
#     # - option("header", "true"): Includes column names
#     data.coalesce(1).write.mode("overwrite").option("header", "true").csv(full_path)

#     print("Data successfully saved to: " + full_path)

In [18]:
# local
def S3_load_data(data, file_name, output_path):
    # SIMULATION for Colab: Write to local folder instead of S3

    # Construct a local path
    local_path = "output/{}/{}".format(output_path, file_name)

    # Write the data
    data.coalesce(1).write.mode("overwrite").option("header", "true").csv(local_path)

    print(f"Simulated S3 save to local folder: {local_path}")

# Test the function with your cleaned dataframe
# We will save it to a folder named "clean_data_output"
S3_load_data(cleaned_df, "cleaned_data", "analytics_output")

# Verify the file was created (Linux command)
!ls -R output/

Simulated S3 save to local folder: output/analytics_output/cleaned_data
output/:
analytics_output

output/analytics_output:
cleaned_data

output/analytics_output/cleaned_data:
part-00000-e438d134-f45e-41df-94a8-e5eb7a5fa16c-c000.csv  _SUCCESS

In [19]:
from pyspark.sql.functions import col, floor, max, concat, lit

def result_1(input_df):
    # 1. Convert price to numeric (integer/double) first, as CSV reads are strings
    # Then calculate INR: floor(price * 86.61)
    df = input_df.withColumn("price_inr", floor(col("price").cast("double") * 86.61))

    # 2. Find the maximum price based on each "neighbourhood_group"
    # We group by neighbourhood_group and aggregate the max of our new price_inr column
    #df_max = df_inr.groupby("neighbourhood_group").agg(max("price_inr").alias("max_val"))
    df = df.groupBy("neighbourhood_group").agg(max("price_inr").alias("max_price_inr"))

    df = df.withColumn("max_price_inr", concat(lit("INR"), col("max_price_inr").cast("int").cast("string")))

    # 3. Add the string "INR" at the foremost of each value
    # We verify the column name matches the sample output: "max_price_inr"

    # Select only the required columns in the correct order
    return df.select("neighbourhood_group", "max_price_inr")

In [20]:
from pyspark.sql.functions import col, count, sum, desc

def result_2(input_df):
    # 1. Filter rows: review_rate_number >= 4 AND host_identity_verified == 'verified'
    # We cast review_rate_number to integer to ensure correct comparison
    filtered_df = input_df.filter(
        (col("review_rate_number").cast("int") >= 4) &
        (col("host_identity_verified") == "verified")
    )

    # 2. Group by "host_name" and calculate aggregates
    # We sum (price + service_fee). We cast them to double to ensure arithmetic works.
    grouped_df = filtered_df.groupBy("host_name").agg(
        count("host_name").alias("count_of_hotels"),
        sum(col("price").cast("double") + col("service_fee").cast("double")).alias("sum_of_total_price")
    )

    # 3. Filter for hosts with 5 or more hotels
    final_filtered_df = grouped_df.filter(col("count_of_hotels") >= 5)

    # 4. Sort by sum_of_total_price in descending order
    sorted_df = final_filtered_df.orderBy(desc("sum_of_total_price"))

    # 5. Return the final dataframe
    return sorted_df

In [21]:
from pyspark.sql.functions import col, round, when, count, dense_rank
from pyspark.sql.window import Window

def result_3(input_df):
    # 1. Create "fee_percentage"
    # Formula: (service_fee / price) * 100
    # Cast columns to double to ensure division works correctly
    df_pct = input_df.withColumn("fee_percentage",
        round((col("service_fee").cast("double") / col("price").cast("double")) * 100, 2)
    )

    # 2. Create "fee_category" using conditional logic (when/otherwise)
    df_cat = df_pct.withColumn("fee_category",
        when(col("fee_percentage") < 10, "Low Fee")
        .when((col("fee_percentage") >= 10) & (col("fee_percentage") <= 20), "Moderate Fee")
        .otherwise("High Fee")
    )

    # 3. Aggregation: Count of "id" named "listing_count"
    # Group by Construction_year, room_type, and the new fee_category
    df_grouped = df_cat.groupBy("Construction_year", "room_type", "fee_category").agg(count("id").alias("listing_count"))

    # 4. Ranking: "dense_rank" (no holes) partitioned by Year, ordered by count DESC
    windowSpec = Window.partitionBy("Construction_year").orderBy(col("listing_count").desc())

    final_df = df_grouped.withColumn("rank", dense_rank().over(windowSpec))

    # 5. Select the final columns in the specific order required
    return final_df.select("Construction_year", "room_type", "fee_category", "listing_count", "rank")

In [22]:
#PART 2
import pandas as pd
import numpy as np

# Create sample data dictionary
data = {
    'id': [1, 2, 3, 4, 5, 6, 7, 8],
    'NAME': [
        'Cozy Studio',
        'Luxury Penthouse',
        'Budget Room',
        'Midtown Castle',
        'Brooklyn Loft',
        'Queens Getaway',
        'Sunny Apartment',
        'Modern Suite'
    ],
    'host_id': [101, 102, 103, 102, 104, 102, 105, 101],
    'host_name': [
        'Michael',
        'Charlotte', # Entry 1 for Charlotte
        'Mike',
        'Charlotte', # Entry 2 for Charlotte (Higher Price)
        'David',
        'Charlotte', # Entry 3 for Charlotte (Lower Price)
        'Sarah',
        'Michael'
    ],
    'neighbourhood_group': ['Brooklyn', 'Manhattan', 'Queens', 'Manhattan', 'Brooklyn', 'Queens', 'Bronx', 'Brooklyn'],
    'neighbourhood': ['Kensington', 'Midtown', 'Astoria', 'Harlem', 'Williamsburg', 'Flushing', 'Fordham', 'Bed-Stuy'],
    'room_type': ['Private room', 'Entire home/apt', 'Private room', 'Entire home/apt', 'Shared room', 'Private room', 'Entire home/apt', 'Private room'],
    'cancellation_policy': ['strict', 'moderate', 'flexible', 'strict', 'moderate', 'flexible', 'strict', 'moderate'],
    'construction_year': [2020, 2015, 2018, 2010, 2021, 2019, 2012, 2022],
    'service_fee': [100, 200, 50, 150, 80, 120, 90, 110],
    'review_rate_number': [4, 5, 3, 4, 2, 5, 4, 3],
    # PRICE is the target variable (y)
    'price': [500, 800, 300, 1200, 400, 600, 750, 550]
}

# Create DataFrame
df = pd.DataFrame(data)

# Save as Excel file (Simulating the S3 file)
# Note: You might need to install openpyxl if it's not present: !pip install openpyxl
df.to_excel("ML_airbnb_cleaned_dataset.xlsx", index=False)

print("Sample dataset created successfully: ML_airbnb_cleaned_dataset.xlsx")
print("\nExpected Answer for q1 (Highest price by Charlotte): 'Midtown Castle' (Price 1200)")
df.head(8)

Sample dataset created successfully: ML_airbnb_cleaned_dataset.xlsx

Expected Answer for q1 (Highest price by Charlotte): 'Midtown Castle' (Price 1200)

,id,NAME,host_id,host_name,neighbourhood_group,neighbourhood,room_type,cancellation_policy,construction_year,service_fee,review_rate_number,price
0,1,Cozy Studio,101,Michael,Brooklyn,Kensington,Private room,strict,2020,100,4,500
1,2,Luxury Penthouse,102,Charlotte,Manhattan,Midtown,Entire home/apt,moderate,2015,200,5,800
2,3,Budget Room,103,Mike,Queens,Astoria,Private room,flexible,2018,50,3,300
3,4,Midtown Castle,102,Charlotte,Manhattan,Harlem,Entire home/apt,strict,2010,150,4,1200
4,5,Brooklyn Loft,104,David,Brooklyn,Williamsburg,Shared room,moderate,2021,80,2,400
5,6,Queens Getaway,102,Charlotte,Queens,Flushing,Private room,flexible,2019,120,5,600
6,7,Sunny Apartment,105,Sarah,Bronx,Fordham,Entire home/apt,strict,2012,90,4,750
7,8,Modern Suite,101,Michael,Brooklyn,Bed-Stuy,Private room,moderate,2022,110,3,550

In [23]:
# Read the local excel file
data = pd.read_excel("ML_airbnb_cleaned_dataset.xlsx")

# Verify it loaded
data.head()

,id,NAME,host_id,host_name,neighbourhood_group,neighbourhood,room_type,cancellation_policy,construction_year,service_fee,review_rate_number,price
0,1,Cozy Studio,101,Michael,Brooklyn,Kensington,Private room,strict,2020,100,4,500
1,2,Luxury Penthouse,102,Charlotte,Manhattan,Midtown,Entire home/apt,moderate,2015,200,5,800
2,3,Budget Room,103,Mike,Queens,Astoria,Private room,flexible,2018,50,3,300
3,4,Midtown Castle,102,Charlotte,Manhattan,Harlem,Entire home/apt,strict,2010,150,4,1200
4,5,Brooklyn Loft,104,David,Brooklyn,Williamsburg,Shared room,moderate,2021,80,2,400

In [24]:
# 1. Filter for host 'Charlotte'
charlotte_data = data[data['host_name'] == 'Charlotte']
print(charlotte_data)

   id              NAME  host_id  host_name neighbourhood_group neighbourhood  \
1   2  Luxury Penthouse      102  Charlotte           Manhattan       Midtown
3   4    Midtown Castle      102  Charlotte           Manhattan        Harlem
5   6    Queens Getaway      102  Charlotte              Queens      Flushing

         room_type cancellation_policy  construction_year  service_fee  \
1  Entire home/apt            moderate               2015          200
3  Entire home/apt              strict               2010          150
5     Private room            flexible               2019          120

   review_rate_number  price
1                   5    800
3                   4   1200
5                   5    600

In [25]:
# 2. Find index of max price
max_price_index = charlotte_data['price'].idxmax()
print(max_price_index)

# 3. Get the name
q1 = charlotte_data.loc[max_price_index, 'NAME']
print(q1)

3
Midtown Castle

In [32]:
from sklearn.preprocessing import LabelEncoder
# 1. Satisfy the requirement: Create the object and store it in 'le_object'
le_object = LabelEncoder()

# 2. Implied Task: actually APPLY it to the data
# (If you don't do this loop, the model training in the next step will fail)
for col in data.columns:
    if data[col].dtype == 'object':
        data[col] = le_object.fit_transform(data[col])

print(data)

   id  NAME  host_id  host_name  neighbourhood_group  neighbourhood  \
0   1     2      101          2                    1              5
1   2     3      102          0                    2              6
2   3     1      103          3                    3              0
3   4     4      102          0                    2              4
4   5     0      104          1                    1              7
5   6     6      102          0                    3              2
6   7     7      105          4                    0              3
7   8     5      101          2                    1              1

   room_type  cancellation_policy  construction_year  service_fee  \
0          1                    2               2020          100
1          0                    1               2015          200
2          1                    0               2018           50
3          0                    2               2010          150
4          2                    1               2021           80
5          1                    0               2019          120
6          0                    2               2012           90
7          1                    1               2022          110

   review_rate_number  price
0                   4    500
1                   5    800
2                   3    300
3                   4   1200
4                   2    400
5                   5    600
6                   4    750
7                   3    550

In [37]:
# Store independent variables (Drop 'price' column)
X = data.drop(columns=['price'])

# Store dependent variable (Select only 'price' column)
y = data['price']

In [38]:
from sklearn.model_selection import train_test_split

# Perform the split according to instructions
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=20)

In [39]:
from sklearn.linear_model import LinearRegression

# 1. Store the model in variable 'model'
model = LinearRegression()

# 2. Train the model (Use .fit with the training data)
model.fit(X_train, y_train)

# 3. Predict values (Use .predict with the test data)
predictions = model.predict(X_test)

predictions

array([362.14892956, 135.84229397])

In [41]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# 1. Mean Absolute Error (MAE)
mae = mean_absolute_error(y_test, predictions)

# 2. Mean Squared Error (MSE)
mse = mean_squared_error(y_test, predictions)

# 3. Root Mean Squared Error (RMSE)
# (Numpy sqrt of MSE)
rmse = np.sqrt(mse)

# 4. R2 Score (Accuracy/Fit)
r2 = r2_score(y_test, predictions)

# Print all measures
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 326.00438823501463
MSE: 114049.86858718158
RMSE: 337.71270125238345
R2 Score: -181.47978973949054